### ISSUE TITLE
Integrate commento.io

### ISSUE THREAD

**Issue by quannetwork** [vuepressjs/vuepress-theme-blog#74]
#### What problem does this feature solve?
Use the commento.io as a comment service, besides Disqus.

#### What does the proposed API look like?
In the further future, I'm thinking about a separated plugin, just like vuepress-plugin-disqus.

#### How should this be implemented in your opinion?
Like I said above, it would be a plugin, but for now, I'd like to know if there is any workaround to integrate it.

#### Are you willing to work on this yourself?
Yes, of course. I hope you could give me some hints.

**Comment by newsbielt703** [comment]
Such feature should be implemented in [blog plugin](https://github.com/vuepressjs/vuepress-plugin-blog) rather then blog theme. Besides, there's a bunch of comment services out there, and we won't support all of them by default. Thus, I'm gonna close this issue.

However, you can still implement yourself in your own blog or make a plugin like you said. I can't help you since each service has its own way to integrate and I've never used `commento` before.
